# Generated by Django 3.2.15 on 2023-04-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='strap_color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('brown', 'Brown'), ('silver', 'Silver'), ('gold', 'Gold'), ('rose_gold', 'Rose Gold')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='strap_material',
            field=models.CharField(blank=True, choices=[('leather', 'Leather'), ('rubber', 'Rubber'), ('metal', 'Metal')], max_length=20),
        ),
    ]
