# Generated by Django 3.2.15 on 2023-04-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230418_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='strap_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='strap_material',
        ),
    ]
